spring:
  application:
    name: authentication-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_library
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

server:
  port: 8092